/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Passage {
  'id' : string,
  'title' : string,
  'content' : string,
  'timeMinutes' : bigint,
}
export interface TestResult {
  'id' : string,
  'wpm' : bigint,
  'userName' : string,
  'passageTitle' : string,
  'mistakes' : bigint,
  'timestamp' : Time,
  'userMobile' : string,
  'accuracy' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'passwordHash' : string,
  'sessionId' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdmin' : ActorMethod<[], undefined>,
  'addPassage' : ActorMethod<[string, string, bigint], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkSessionValid' : ActorMethod<[string, string], boolean>,
  'deletePassage' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPassages' : ActorMethod<[], Array<Passage>>,
  'getTestResults' : ActorMethod<[], Array<TestResult>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : { 'name' : string, 'sessionId' : string, 'mobile' : string } } |
      { 'err' : string }
  >,
  'logout' : ActorMethod<[string], undefined>,
  'registerUser' : ActorMethod<[string, string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'submitTestResult' : ActorMethod<
    [string, string, string, bigint, bigint, bigint],
    undefined
  >,
  'updatePassage' : ActorMethod<
    [string, string, string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];